import { View } from 'react-native'
import { ProjectList } from '../components/ProjectList'
import { Project } from '../models/Project'
import { singleColor, colors } from '../../Shared/models'
import { status } from '../../Shared/models'

const projects: Project[] = [
    {"id":1,"project_title":"Cogibox","project_description":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.blueish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"VictorMono"},
    {"id":2,"project_title":"BlogXS","project_description":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.greenish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"VictorMono"},
    {"id":3,"project_title":"Shufflebeat","project_description":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.light,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"VictorMono"},
    {"id":4,"project_title":"Centizu","project_description":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.yellowish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"IBMPlexSans"},
    {"id":5,"project_title":"Riffpedia","project_description":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.greenish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"IBMPlexSans"},
    {"id":6,"project_title":"Roomm","project_description":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.blueish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"NotoSerif"},
    {"id":7,"project_title":"Browsecat","project_description":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.yellowish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"NotoSerif"},
    {"id":8,"project_title":"Babbleopia","project_description":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.light,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"NotoSerif"},
    {"id":9,"project_title":"Meemm","project_description":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.greenish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"VictorMono"},
    {"id":10,"project_title":"Gigaclub","project_description":"Fusce consequat. Nulla nisl. Nunc nisl.","project_due_date":new Date(),"project_created_on":new Date(),"project_completed_on":new Date(),"project_color":colors.greenish,"project_status":status.created,"project_icon":"inbox","project_fontFamily":"VictorMono"}
]

export function ToDoScreen() {
    return (
        <View style={{ top: 25 }} >
            <ProjectList projectList={projects}/>
        </View>
    )
}